name: Test Vue App
on: push
jobs:
  runs-on: windows-latest
  steps:
    - name: Get the repository code
      uses: actions/checkout@v3
    - name: Install dependencies
      run: npm ci
    - name: Test application
      run: npm run test